<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CharityRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CharityRepository extends EntityRepository
{
    public function findAllCharities($sortmode)
    {
        $dql = "SELECT c
                FROM AppBundle:Charity c
                ORDER BY c.createdAt DESC";

        return $this->getEntityManager()
            ->createQuery($dql);
    }

    public function findAllCharitiesByUser($slug, $sortmode)
    {
        $dql = "SELECT c, u
                FROM AppBundle:Charity c
                JOIN c.user u
                WHERE u.slug = :slug
                ORDER BY c.createdAt DESC";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('slug', $slug);
    }

    public function findAllCharitiesByCategory($slug, $sortmode)
    {
        $dql = "SELECT c, ct
                FROM AppBundle:Charity c
                JOIN c.category ct
                WHERE ct.slug = :slug
                ORDER BY c.createdAt DESC";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('slug', $slug);
    }

    public function findAllCharitiesByTag($slug, $sortmode)
    {
        $dql = "SELECT c, t
                FROM AppBundle:Charity c
                LEFT JOIN c.tags t
                WHERE t.slug = :slug
                ORDER BY c.createdAt DESC";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('slug', $slug);
    }

    public function findTopImportantCharities($count)
    {
        $dql = "SELECT c
                FROM AppBundle:Charity c
                WHERE c.isActive = true
                ORDER BY c.ratingCount / c.viewCount DESC";
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult(1)
            ->setMaxResults($count)
            ->getResult();
    }

    public function findTopActiveCharities($count)
    {
        $dql = "SELECT c
                FROM AppBundle:Charity c
                WHERE c.isActive = true
                ORDER BY c.createdAt DESC";
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult(1)
            ->setMaxResults($count)
            ->getResult();
    }

    public function findTopCompletedCharities($count)
    {
        $dql = "SELECT c
                FROM AppBundle:Charity c
                WHERE c.isActive = false
                ORDER BY c.createdAt DESC";
        return $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult(1)
            ->setMaxResults($count)
            ->getResult();
    }
}
