<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function loadUserBySocialId($id)
    {
        $dql = "SELECT u
                FROM 'AppBundle:User' u
                WHERE u.googleId = :id
                OR u.vkontakteId = :id
                OR u.facebookId = :id";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }

}
