<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllTagsByPopularity()
    {
        $dql = "SELECT t
                FROM AppBundle:Tag t
                ORDER BY SIZE(t.charities) DESC";
        return $this->getEntityManager()
            ->createQuery($dql)
            ->getResult();
    }

    public function findAllTags()
    {
        $dql = "SELECT t
                FROM AppBundle:Tag t
                ORDER BY t.tagName ASC";
        return $this->getEntityManager()
            ->createQuery($dql);
    }
}
