<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
        $dql = "SELECT u
                FROM 'AppBundle:User' u
                WHERE u.username = :username
                OR u.email = :email";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getOneOrNullResult();
    }

    public function loadUserBySocialIdAndEmail($id, $email)
    {
        $dql = "SELECT u
                FROM 'AppBundle:User' u
                WHERE u.email = :email
                AND (u.googleId = :id
                OR u.vkontakteId = :id
                OR u.facebookId = :id)";

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameter('id', $id)
            ->setParameter('email', $email)
            ->getOneOrNullResult();
    }
}
