parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     CharityPlatform
    database_name_test:     CharityPlatform_test
    database_user:     root
    database_password: ~

    mailer_transport:  gmail
    mailer_host:       smtp.gmail.com
    mailer_port:       465
    mailer_encryption: ssl
    mailer_user:       ~
    mailer_password:   ~

    secret:            ThisTokenIsNotSoSecretChangeIt
    app.dir: "%kernel.root_dir%/../"

    # Number of elements in paginator line on index page
    app.paginator_length: 5
    # Number of charities on each page
    app.paginator_count_per_page: 5
    # Number of elements in paginator line on index page in cabinet
    app.cabinet_paginator_length: 5
    # Number of items on each page in cabinet
    app.cabinet_paginator_count_per_page: 15

    vkontakte_app_id: 5399895
    vkontakte_app_secret: 7fFdVqlrdQ0pIun34I8b
    facebook_app_id: 1020999824602547
    facebook_app_secret: bcaa5454a5e1ca4839a1b164aa09bad9
    google_app_id: 929543229226-v98krb32p67qabj2lfpfhhlhbk89ek58.apps.googleusercontent.com
    google_app_secret: GCaFPCS_Z2WmZtRzDFR3zLDw
