security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
#            algorithm: bcrypt
#            cost: 13
        AppBundle\Entity\User: plaintext
#            algorithm: bcrypt
#            cost: 13

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]

        in_memory:
            memory:
                users:
                    SuperAdmin:
                        password: qwerty
                        roles: 'ROLE_SUPER_ADMIN'
                    Test_Admin:
                        password: qwerty
                        roles: 'ROLE_ADMIN'
                    Test_Moderator:
                        password: qwerty
                        roles: 'ROLE_MODERATOR'
                    Test_User:
                        password: qwerty
                        roles: 'ROLE_USER'

        user_db:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~

            form_login:
                provider: chain_provider
                login_path: /login
                check_path: /login_check
                username_parameter: form[username]
                password_parameter: form[password]

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/cabinet, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_MODERATOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]