<?php

namespace AppBundle\Twig;

use AppBundle\Services\MenuManager;

class AppExtension extends \Twig_Extension
{
    protected $menuManager;

    /**
     * AppExtension constructor.
     * @param $menuManager
     */
    public function __construct(MenuManager $menuManager)
    {
        $this->menuManager = $menuManager;
    }

    public function getFilters()
    {
        return parent::getFilters(); // TODO: Change the autogenerated stub
    }

    public function getFunctions()
    {
        return [
            new \Twig_SimpleFunction('page_title', [$this, 'getPageTitle']),
            new \Twig_SimpleFunction('all_categories', [$this, 'getAllCategories']),
            new \Twig_SimpleFunction('bread_crumbs', [$this, 'getBreadCrumbs']),
            new \Twig_SimpleFunction('available_languages', [$this, 'getAvailableLanguages']),
            new \Twig_SimpleFunction('current_language', [$this, 'getCurrentLanguage']),
            new \Twig_SimpleFunction('available_cities', [$this, 'getAvailableCities']),
            new \Twig_SimpleFunction('current_city', [$this, 'getCurrentCity']),
            new \Twig_SimpleFunction('important_charities', [$this, 'getImportantCharities']),
            new \Twig_SimpleFunction('active_charities', [$this, 'getActiveCharities']),
            new \Twig_SimpleFunction('completed_charities', [$this, 'getCompletedCharities']),
            new \Twig_SimpleFunction('tag_cloud_elements', [$this, 'getTagCloudElements']),
        ];
    }

    public function getPageTitle()
    {
        return $this->menuManager->getPageTitle();
    }

    public function getAllCategories()
    {
        return $this->menuManager->getAllCategories();
    }

    public function getBreadCrumbs()
    {
        return $this->menuManager->getBreadCrumbs();
    }

    public function getAvailableLanguages()
    {
        return $this->menuManager->getAvailableLanguages();
    }

    public function getCurrentLanguage()
    {
        return $this->menuManager->getCurrentLanguage();
    }

    public function getAvailableCities()
    {
        return $this->menuManager->getAvailableCities();
    }

    public function getCurrentCity()
    {
        return $this->menuManager->getCurrentCity();
    }

    public function getImportantCharities()
    {
        return $this->menuManager->getImportantCharities();
    }

    public function getActiveCharities()
    {
        return $this->menuManager->getActiveCharities();
    }

    public function getCompletedCharities()
    {
        return $this->menuManager->getCompletedCharities();
    }

    public function getTagCloudElements()
    {
        return $this->menuManager->getTagCloudElements();
    }

    public function getName()
    {
        return 'app_extension';
    }
}